Add `spec-fetcher` for santa
riiid/riiidx pull request #10
Opened 2023-01-16 07:07 UTC by hyo-choi

- openAPI spec fetch용으로 만든 스크립트인데, 다른 챕터에서도 필요하시면 사용하시라고 이쪽에 올려봅니다.

2023-01-17 03:54 UTC, haenah-riiid commented on src/team/component/santa/spec-fetcher/src/fetcher.ts
> +        --pattern ${SPEC_FILE_NAME} \
이거 glob 패턴이라서 input도 filename이 아니라 filenamePattern 해놓고 description에 'glob 패턴으로 기입해주세요' 하면 되지 않을까요? 대다수의 레포에서 `*spec.json` 으로 가져오게 될 것 같아서요

2023-01-17 03:56 UTC, haenah-riiid requested changes
💪

2023-01-17 04:55 UTC, hyo-choi commented on src/team/component/santa/spec-fetcher/src/fetcher.ts
> +        --pattern ${SPEC_FILE_NAME} \
✅ 6106de873b20110adcc7729ed2b3d0c8e072e8e7...75d2b76fa0db735236c260035cea145e7cc08d3a
glob 매칭 지원 추가했습니다 👍

2023-01-17 08:13 UTC, SongJiyeon approved these changes
👍 최고최고 좋아용 👍

2023-01-17 23:05 UTC, SongJiyeon commented on src/team/component/santa/spec-fetcher/README.md
> +spec 파일들은 각각 `path-to-output-directory/username/repository` 경로에
❓ 생성된 spec을 깃으로 관리할거라면 username이 path에 들어가는게 불편할 것 같아요 만들때마다 만든 사람 이름에 따른 경로가 새로 생겨서요 혹시 username이 path에 들어가는 이유가 있을까요?

2023-01-18 00:15 UTC, haenah-riiid commented on src/team/component/santa/spec-fetcher/src/fetcher.ts
> +        --pattern ${SPEC_FILE_NAME} \
앗 inputname filenamePattern 인쪽이 좋지 않을까 생각됩니다.

2023-01-18 00:34 UTC, hyo-choi commented on src/team/component/santa/spec-fetcher/README.md
> +spec 파일들은 각각 `path-to-output-directory/username/repository` 경로에
1. github이 username만 다르면 같은 이름의 repository 생성이 가능해서 혹시! 모를 문제상황 방지를 위해 이렇게 생성되도록 했습니다.
2. 폴라포를 벤치마킹해 만들어서 그대로 한 것도 있기는 합니다. (ㅋㅋ)

2023-01-18 00:44 UTC, hyo-choi commented on src/team/component/santa/spec-fetcher/src/fetcher.ts
> +        --pattern ${SPEC_FILE_NAME} \
`filename-pattern` -> `filename` 했던 커밋을 날렸습니다 👍

2023-01-18 00:51 UTC, hyo-choi commented on src/team/component/santa/spec-fetcher/README.md
> +spec 파일들은 각각 `path-to-output-directory/username/repository` 경로에
(구두 논의사항) 이 username은 레포지토리 주인(?)(이 레포의 경우 `riiid`)의 username이기 때문에 계속 유지됩니다 👍

2023-01-18 00:54 UTC, haenah-riiid approved these changes

2023-01-18 01:08 UTC, merged